const buckets = [
  {
    kind: "storage#bucket",
    selfLink:
      "https://www.googleapis.com/storage/v1/b/artifacts.wbtg63wxu.appspot.com",
    id: "artifacts.wbtg63wxu.appspot.com",
    name: "artifacts.wbtg63wxu.appspot.com",
    projectNumber: "156784354855",
    metageneration: "1",
    location: "US",
    storageClass: "STANDARD",
    etag: "CAE=",
    timeCreated: "2021-08-02T18:09:05.536Z",
    updated: "2021-08-02T18:09:05.536Z",
    iamConfiguration: {
      bucketPolicyOnly: { enabled: false },
      uniformBucketLevelAccess: { enabled: false },
      publicAccessPrevention: "unspecified",
    },
    locationType: "multi-region",
    rpo: "DEFAULT",
  },
  {
    kind: "storage#bucket",
    selfLink:
      "https://www.googleapis.com/storage/v1/b/demo-3-data-storage-bucket",
    id: "demo-3-data-storage-bucket",
    name: "demo-3-data-storage-bucket",
    projectNumber: "156784354855",
    metageneration: "1",
    location: "US-EAST4",
    storageClass: "STANDARD",
    etag: "CAE=",
    timeCreated: "2021-10-13T16:12:48.597Z",
    updated: "2021-10-13T16:12:48.597Z",
    iamConfiguration: {
      bucketPolicyOnly: { enabled: false },
      uniformBucketLevelAccess: { enabled: false },
      publicAccessPrevention: "unspecified",
    },
    locationType: "region",
  },
  {
    kind: "storage#bucket",
    selfLink:
      "https://www.googleapis.com/storage/v1/b/staging.wbtg63wxu.appspot.com",
    id: "staging.wbtg63wxu.appspot.com",
    name: "staging.wbtg63wxu.appspot.com",
    projectNumber: "156784354855",
    metageneration: "1",
    location: "US-EAST4",
    storageClass: "STANDARD",
    etag: "CAE=",
    timeCreated: "2021-09-30T19:50:26.193Z",
    updated: "2021-09-30T19:50:26.193Z",
    lifecycle: { rule: [[Object]] },
    iamConfiguration: {
      bucketPolicyOnly: { enabled: false },
      uniformBucketLevelAccess: { enabled: false },
      publicAccessPrevention: "unspecified",
    },
    locationType: "region",
  },
  {
    kind: "storage#bucket",
    selfLink: "https://www.googleapis.com/storage/v1/b/wbtg63wxu.appspot.com",
    id: "wbtg63wxu.appspot.com",
    name: "wbtg63wxu.appspot.com",
    projectNumber: "156784354855",
    metageneration: "1",
    location: "US-EAST4",
    storageClass: "STANDARD",
    etag: "CAE=",
    timeCreated: "2021-09-30T19:50:26.191Z",
    updated: "2021-09-30T19:50:26.191Z",
    iamConfiguration: {
      bucketPolicyOnly: { enabled: false },
      uniformBucketLevelAccess: { enabled: false },
      publicAccessPrevention: "unspecified",
    },
    locationType: "region",
  },
  {
    kind: "storage#bucket",
    selfLink: "https://www.googleapis.com/storage/v1/b/wbtg63wxu_cloudbuild",
    id: "wbtg63wxu_cloudbuild",
    name: "wbtg63wxu_cloudbuild",
    projectNumber: "156784354855",
    metageneration: "1",
    location: "US",
    storageClass: "STANDARD",
    etag: "CAE=",
    timeCreated: "2021-08-02T18:08:21.568Z",
    updated: "2021-08-02T18:08:21.568Z",
    iamConfiguration: {
      bucketPolicyOnly: { enabled: false },
      uniformBucketLevelAccess: { enabled: false },
      publicAccessPrevention: "unspecified",
    },
    locationType: "multi-region",
    rpo: "DEFAULT",
  },
];

export default buckets;
