steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/${_IMAGE}", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_IMAGE}"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE}",
        "--image",
        "gcr.io/$PROJECT_ID/${_IMAGE}",
        "--region",
        "${_REGION}",
      ]
substitutions:
  _IMAGE: basic-express-container
  _SERVICE: basic-express-microservice
  _REGION: us-east4
  # https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
images:
  - gcr.io/$PROJECT_ID/${_IMAGE}
# https://cloud.google.com/build/docs/building/build-containers#store-images
# "If you want to store the image as part of your build flow and want to display the image in the build results, use both the Docker push command and the images field in your build config file."

# https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
