steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_IMAGE}:latest",
        ".",
        "-f",
        "nodejs-containers/storage-crud/Dockerfile",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_IMAGE}:latest",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE}",
        "--image",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_IMAGE}:latest",
        "--region",
        "${_REGION}",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMAGE_REPO: nodejs-containers
  _IMAGE: storage-crud-container
  _SERVICE: storage-crud-microservice
  _REGION: us-east4
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_REPO}/${_IMAGE}:latest
